jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - continue-on-error: true
      name: Build with Ant
      run: 'sed -i ''s#<input .*/>##'' build.xml

        ant clean dist

        '
      working-directory: ./build
    - continue-on-error: true
      name: Install X virtual framebuffer
      run: sudo apt-get install -y xvfb
    - continue-on-error: true
      name: Run tests
      run: xvfb-run --auto-servernum --server-args "-screen 0 1024x768x24" ant test
        -Drunning-from-github-action=1
      working-directory: ./app
    - continue-on-error: true
      name: Publish results
      uses: actions/upload-artifact@v1
      with:
        name: html-results
        path: app/test-bin/results/html/
    - continue-on-error: true
      name: Cleanup xvfb
      uses: bcomnes/cleanup-xvfb@v1
name: Java CI
on:
  repository_dispatch:
    types: trigger-ga___ant.yml
